apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: production
  labels:
    app: jenkins
    secret-access: "true"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: new-secret1
