apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: production
  labels:
    app: mariadb
    secret-access: "true"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "YourStrongRootPassword" # Hardcoded password here
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: new-secret1
