apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: production
  labels:
    app: node
    secret-access: "true"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: node
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: new-secret1
