apiVersion: v1
kind: ConfigMap
metadata:
  name: blocked-accounts-config
  namespace: kubekeeper
data:
  config.json: |
    {
      "blockedAccounts": [
        {"namespace": "production", "serviceAccount": "kubernetes-apps"}
      ]
    }