apiVersion: v1
kind: Secret
metadata:
  name: new-secret
  labels:
    protected-secret: "true"
  namespace: production
  annotations:
   secret-ownership: "nginx-deployment:Deployment:production;redis-deployment:Deployment:production;node-deployment:Deployment:production;python-deployment:Deployment:production;postgres-deployment:Deployment:production;tensorflow-deployment:Deployment:production;elasticsearch-deployment:Deployment:production;jenkins-deployment:Deployment:production"
type: Opaque
data:
  secretdata: bmV3dGVzdAo=